### ISSUE TITLE
Save/Restore config

### ISSUE THREAD

**Issue by robinmordasiewicz** [egtzori/atem_cli#1]
Is there any way that you can think of to enable saving/restoring an Atem config from the cli. I don’t want to use the desktop software to restore configs.

**Comment by egtzori** [comment]
The best i can think of is bash script with list of commands to upload the desired settings

**Comment by egtzori** [comment]
The best i can think of is bash script with list of commands to upload the desired settings

like:

update_settings.sh

```
./atem_cli 1.2.3.4 program ${PROGRAM}
./atem_cli 1.2.3.4 preview ${PREVIEW}
...
```

saving is the same,
PROGRAM=<atem command>

I dont have the hardware near me now and i cannot upload complete example but you get the idea :)

**Comment by robinmordasiewicz** [comment]
But to upload file to the media player as well as uploading new Macros and audio state, or just the whole xml config would be best.

—
Robin Mordasiewicz
________________________________
